ACET_WEB/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACET_WEB.Controllers
{
	[Authorize(Roles = "Administrator")]
    public class AnswerController : Controller
    {
        private acet_dbEntities db = new acet_dbEntities();

        //
        // GET: /Answer/

        public ActionResult Index(int question=0)
        {
            ViewBag.gid = question;
            var answers = db.Answers.Include("Question");
            if (db.Questions.FirstOrDefault(p => p.Id == question) != null)
            {
                return View(answers.Where(q => q.QuestionId == question).ToList());
            }
            return View(answers.ToList());
        }

        //
        // GET: /Answer/Details/5

        public ActionResult Details(int id = 0)
        {
            Answer answer = db.Answers.Single(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        //
        // GET: /Answer/Create

        public ActionResult Create(int question=0)
        {
            ViewBag.gid = question;
            var qg = db.Questions.FirstOrDefault(p => p.Id == question);
            if (qg != null)
            {
                ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Question1", qg.Id);
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Question1");
            return View();
        }

        //
        // POST: /Answer/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.AddObject(answer);
                db.SaveChanges();
                return RedirectToAction("Index", new  { question=answer.QuestionId});
            }

            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Question1", answer.QuestionId);
            return View(answer);
        }

        //
        // GET: /Answer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Answer answer = db.Answers.Single(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Question1", answer.QuestionId);
            return View(answer);
        }

        //
        // POST: /Answer/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Attach(answer);
                db.ObjectStateManager.ChangeObjectState(answer, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index", new { question = answer.QuestionId });
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Question1", answer.QuestionId);
            return View(answer);
        }

        //
        // GET: /Answer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Answer answer = db.Answers.Single(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        //
        // POST: /Answer/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Single(a => a.Id == id);
            var question = answer.QuestionId;
            db.Answers.DeleteObject(answer);
            db.SaveChanges();
            return RedirectToAction("Index", new { question = question });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ACET_WEB/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACET_WEB.Controllers
{
	[Authorize(Roles = "Administrator")]
	public class QuestionController : Controller
    {
        private acet_dbEntities db = new acet_dbEntities();

        //
        // GET: /Question/

        public ActionResult Index(int group=0)
        {
            ViewBag.gid = group;
            var questions = db.Questions.Include("QuestionGroup");
            if (db.QuestionGroups.FirstOrDefault(p=>p.Id==group)!=null)
            {
                
                return View(questions.Where(q => q.QuestionGroup.Id == group).ToList());
            }
            return View(questions.ToList());
        }

        //
        // GET: /Question/Details/5

        public ActionResult Details(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // GET: /Question/Create

        public ActionResult Create(int group = 0)
        {
            ViewBag.gid = group;
            var qg = db.QuestionGroups.FirstOrDefault(p => p.Id == group);
            if (qg != null)
            {
                ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", qg.Id);
            }
            else
            {
                ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name");
            }
           
            return View();
        }

        //
        // POST: /Question/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.AddObject(question);
                db.SaveChanges();
                return RedirectToAction("Index", new { group=question.GroupId});
            }

            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // GET: /Question/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // POST: /Question/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Attach(question);
                db.ObjectStateManager.ChangeObjectState(question, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index", new { group = question.GroupId });
            }
            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // GET: /Question/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            var group = question.GroupId;
            db.Questions.DeleteObject(question);
            db.SaveChanges();
            return RedirectToAction("Index", new { group = group });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ACET_WEB/Views/Question/Create.cshtml
@model ACET_WEB.Question

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('Desc', {
        });

    </script>
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    ViewBag.Title = "Group Question Editor";
}

<div class="page-header">
    <h1>
        Question Editor
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Question1)
                </div>
                <div class="editor-field form-group">
                    @Html.TextAreaFor(model => model.Question1, new { @class="form-control"})
                    @Html.ValidationMessageFor(model => model.Question1)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Number)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Number)
                    @Html.ValidationMessageFor(model => model.Number)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.AnswerKey)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AnswerKey)
                    @Html.ValidationMessageFor(model => model.AnswerKey)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Status)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupId, "QuestionGroup")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("GroupId", String.Empty)
                    @Html.ValidationMessageFor(model => model.GroupId)
                </div>
                <br/>
                <p>
                    <input class="btn btn-primary" type="submit" value="Create" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index", new { group = ViewBag.gid })
        </div>
</div></div>

ACET_WEB/Views/Question/Delete.cshtml
@model ACET_WEB.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Question</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Question1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Question1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Modified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modified)
    </div>


    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.QuestionGroup.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.QuestionGroup.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index", new { group = Model.GroupId })
    </p>
}

ACET_WEB/Views/Question/Details.cshtml
@model ACET_WEB.Question

@{
    ViewBag.Title = "Details";
}
@{
    ViewBag.Title = "Add New Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('post_content_vi', {
        });

    </script>
}
@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h1>
        Group Question
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">


        <fieldset>
            <legend>Question</legend>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.Question1)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Question1)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.Number)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Number)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.Created)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Created)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.Modified)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Modified)
            </div>

           
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Status)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Status)
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.QuestionGroup.Name)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.QuestionGroup.Name)
            </div>
        </fieldset>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
</div>
</div>

ACET_WEB/Views/Question/Edit.cshtml
@model ACET_WEB.Question

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('Desc', {
        });

    </script>
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    ViewBag.Title = "Question Editor";
}

<div class="page-header">
    <h1>
        Question Editor
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Question</legend>

                @Html.HiddenFor(model => model.Id)

                <div class="editor-label">
                    @Html.LabelFor(model => model.Question1)
                </div>
                <div class="editor-field form-group">
                    @Html.TextAreaFor(model => model.Question1, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Question1)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Number)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Number)
                    @Html.ValidationMessageFor(model => model.Number)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.AnswerKey)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AnswerKey)
                    @Html.ValidationMessageFor(model => model.AnswerKey)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Status)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.GroupId, "QuestionGroup")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("GroupId", String.Empty)
                    @Html.ValidationMessageFor(model => model.GroupId)
                </div>
                <br/>
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index",  new  { group=Model.GroupId})
        </div>

       </div></div>

ACET_WEB/Views/Question/Index.cshtml
@model IEnumerable<ACET_WEB.Question>

@{
    ViewBag.Title = "Add New Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('post_content_vi', {
        });

    </script>
}
@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h1>
        Group Question
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">


        <p>
            @Html.ActionLink("Create New", "Create", new  { group=ViewBag.gid})
        </p>
        <table class="table table-bordered table-striped" >
            <tr>
                <th>
                  Question
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Modified)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AnswerKey)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestionGroup.Name)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Question1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modified)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnswerKey)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestionGroup.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("List Answer", "Index", "Answer", new { question = item.Id }, new  { }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
</div></div>