ACET_WEB/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACET_WEB.Controllers
{
	[Authorize(Roles = "Administrator")]
	public class QuestionController : Controller
    {
        private acet_dbEntities db = new acet_dbEntities();

        //
        // GET: /Question/

        public ActionResult Index(int group=0)
        {
            ViewBag.gid = group;
            var questions = db.Questions.Include("QuestionGroup");
            if (db.QuestionGroups.FirstOrDefault(p=>p.Id==group)!=null)
            {
                
                return View(questions.Where(q => q.QuestionGroup.Id == group).ToList());
            }
            return View(questions.ToList());
        }

        //
        // GET: /Question/Details/5

        public ActionResult Details(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // GET: /Question/Create

        public ActionResult Create(int group = 0)
        {
            ViewBag.gid = group;
            var qg = db.QuestionGroups.FirstOrDefault(p => p.Id == group);
            if (qg != null)
            {
                ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", qg.Id);
            }
            else
            {
                ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name");
            }
           
            return View();
        }

        //
        // POST: /Question/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.AddObject(question);
                db.SaveChanges();
                return RedirectToAction("Index", new { group=question.GroupId});
            }

            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // GET: /Question/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // POST: /Question/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Attach(question);
                db.ObjectStateManager.ChangeObjectState(question, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index", new { group = question.GroupId });
            }
            ViewBag.GroupId = new SelectList(db.QuestionGroups, "Id", "Name", question.GroupId);
            return View(question);
        }

        //
        // GET: /Question/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Single(q => q.Id == id);
            var group = question.GroupId;
            db.Questions.DeleteObject(question);
            db.SaveChanges();
            return RedirectToAction("Index", new { group = group });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ACET_WEB/Controllers/QuestionGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACET_WEB.Controllers
{
	[Authorize(Roles = "Administrator")]
    public class QuestionGroupController : Controller
    {
        private acet_dbEntities db = new acet_dbEntities();

        //
        // GET: /QuestionGroup/

        public ActionResult Index()
        {
            return View(db.QuestionGroups.ToList());
        }

        //
        // GET: /QuestionGroup/Details/5

        public ActionResult Details(int id = 0)
        {
            QuestionGroup questiongroup = db.QuestionGroups.Single(q => q.Id == id);
            if (questiongroup == null)
            {
                return HttpNotFound();
            }
            return View(questiongroup);
        }

        //
        // GET: /QuestionGroup/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /QuestionGroup/Create

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(QuestionGroup questiongroup)
        {
            if (ModelState.IsValid)
            {
                db.QuestionGroups.AddObject(questiongroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questiongroup);
        }

        //
        // GET: /QuestionGroup/Edit/5
        public ActionResult Edit(int id = 0)
        {
            QuestionGroup questiongroup = db.QuestionGroups.Single(q => q.Id == id);
            if (questiongroup == null)
            {
                return HttpNotFound();
            }
            return View(questiongroup);
        }

        //
        // POST: /QuestionGroup/Edit/5

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(QuestionGroup questiongroup)
        {
            if (ModelState.IsValid)
            {
                db.QuestionGroups.Attach(questiongroup);
                db.ObjectStateManager.ChangeObjectState(questiongroup, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(questiongroup);
        }

        //
        // GET: /QuestionGroup/Delete/5

        public ActionResult Delete(int id = 0)
        {
            QuestionGroup questiongroup = db.QuestionGroups.Single(q => q.Id == id);
            if (questiongroup == null)
            {
                return HttpNotFound();
            }
            return View(questiongroup);
        }

        //
        // POST: /QuestionGroup/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuestionGroup questiongroup = db.QuestionGroups.Single(q => q.Id == id);
            db.QuestionGroups.DeleteObject(questiongroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ACET_WEB/Views/QuestionGroup/Create.cshtml
@model ACET_WEB.QuestionGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('Desc', {
        });

    </script>
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    ViewBag.Title = "Group Question Editor";
}

<div class="page-header">
    <h1>
        Group Question Editor
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field form-group">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Desc)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Desc)
                    @Html.ValidationMessageFor(model => model.Desc)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Status)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Type)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Type)
                    @Html.ValidationMessageFor(model => model.Type)
                </div>
                <br />
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

 
</div>
</div>

ACET_WEB/Views/QuestionGroup/Delete.cshtml
@model ACET_WEB.QuestionGroup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>QuestionGroup</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Desc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Desc)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Modified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ACET_WEB/Views/QuestionGroup/Details.cshtml
@model ACET_WEB.QuestionGroup


@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('post_content_vi', {
        });

    </script>
}
@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h1>
        Group Question Details
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        <fieldset>

            <div class="display-label">
                <b>  @Html.DisplayNameFor(model => model.Name)</b> 
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="display-label">
                <b> @Html.DisplayNameFor(model => model.Desc)</b>
            </div>
            <div class="display-field">
                @Html.DisplayTextFor(model => model.Desc)
            </div>

            <div class="display-label">
                <b>   @Html.DisplayNameFor(model => model.Created)</b> 
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Created)
            </div>

            <div class="display-label">
                <b>   @Html.DisplayNameFor(model => model.Modified)</b> 
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Modified)
            </div>

            <div class="display-label">
                <b>  @Html.DisplayNameFor(model => model.Status)</b>    
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Status)
            </div>

            <div class="display-label">
                <b>   @Html.DisplayNameFor(model => model.Type)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Type)
            </div>
        </fieldset>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
</div>
</div>

ACET_WEB/Views/QuestionGroup/Edit.cshtml
@model ACET_WEB.QuestionGroup


@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('Desc', {
        });

    </script>
@Scripts.Render("~/bundles/jqueryval")
}
@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h1>
        Group Question Editor
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>

                @Html.HiddenFor(model => model.Id)

                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field form-group">
                    @Html.TextBoxFor(model => model.Name, new { @class="form-control"})
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Desc)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Desc)
                    @Html.ValidationMessageFor(model => model.Desc)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Status)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Type)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Type)
                    @Html.ValidationMessageFor(model => model.Type)
                </div>
                <br/>
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

     
</div>
</div>

ACET_WEB/Views/QuestionGroup/Index.cshtml
@model IEnumerable<ACET_WEB.QuestionGroup>
@{
    ViewBag.Title = "Add New Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AddToHeadCss{
    <link rel="stylesheet" href="@Url.Content("/assets/css/jquery-ui.custom.min.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/chosen.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-timepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/daterangepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/bootstrap-datetimepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("/assets/css/colorpicker.css")" />
}
@section AddToEndBodyJs{
    <script src="@Url.Content("/Content/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("/Content/ckfinder/ckfinder.js")"></script>
    <script src="/assets/js/jquery.validate.min.js"></script>
    <script src="/assets/js/additional-methods.min.js"></script>
    <script src="/assets/js/bootbox.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace('post_content_vi', {
        });

    </script>
}
@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h1>
        Group Question
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table table-bordered table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
               
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Modified)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modified)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("List Question", "Index", "Question", new { group = item.Id }, new { }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>